[server]
host = "127.0.0.1"
port = 3000

[database]
url = "mysql://root:root123@192.168.100.149:3306/webserver-template"

[redis]
url = "redis://192.168.100.149:6379/"

[jwt]
secret = "xkL9mN2pQrS4tU6vW8yZ1aB3cD5eF7gH0iJ8kL2mN4oP6qR8sT0uV2wX4yZ6aB8cD0eF2gH"
expiration_hours = 24