[server]
host = "127.0.0.1"
port = 3000

[database]
url = "postgres://postgres:postgres@localhost/myapp"

[redis]
url = "redis://127.0.0.1:6379/"

[jwt]
secret = "your-secret-key-change-this-in-production"
expiration_hours = 24