listen_addr = "127.0.0.1:3000"

[server]
host = "127.0.0.1"
port = 3000

[database]
url = "mysql://root:root123@192.168.100.149:3306/webserver_template"
pool_size = 10
connection_timeout = 30000
statement_timeout = 30000

[redis]
url = "redis://192.168.100.149:6379/"

[jwt]
secret = "xkL9mN2pQrS4tU6vW8yZ1aB3cD5eF7gH0iJ8kL2mN4oP6qR8sT0uV2wX4yZ6aB8cD0eF2gH"
expiry = 86400  # 24小时，单位：秒

[log]
filter_level = "info"
with_ansi = true
stdout = false
directory = "./logs"
file_name = "app.log"
rolling = "daily"
format = "full"
with_level = true
with_target = true
with_thread_ids = true
with_thread_names = true
with_source_location = true

# 可选的 TLS 配置
# [tls]
# cert = "path/to/cert.pem"
# key = "path/to/key.pem"
